Add friends likes
IgorShurov/java-filmorate pull request #5
Opened 2023-11-22 21:24 UTC by IgorShurov

Изменена архитектура приложения с учетом ТЗ-10, пришлось переделать почти полностью проект.
Добавлена возможность добавления в друзья.
Приложение приведено к соответствию REST.

2023-11-23 19:03 UTC, Frilock requested changes
Добрый вечер, в целом хорошая работа, ряд небольших комментариев и можно принимать

2023-11-23 19:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Правильнее инжектить в класс интерфейс, а не его реализацию

2023-11-23 19:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage userStorage;
Правильнее инжектить интерфейс

2023-11-23 19:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Integer id = 1;
Можно static

2023-11-23 19:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private Integer id = 1;
Можно статик

2023-11-23 19:03 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +        } else if (film.getName() == null || film.getName().isBlank()) {
Лучше заменить на StringUtils.isNotBlank

2023-11-23 19:51 UTC, merged

2023-11-23 20:08 UTC, IgorShurov commented
Случайно объединил ветку...

2023-11-24 06:14 UTC, Frilock reviewed
Принято