Add database
IgorShurov/java-filmorate pull request #7
Opened 2023-12-14 23:57 UTC by IgorShurov

Создана схема БД.
Реализована БД.
Реализована бизнес логика ТЗ 11.
Локальное хранение данных перенесено в БД

2023-12-15 16:49 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/mpa/MpaNotFoundException.java
> +public class MpaNotFoundException extends RuntimeException {
Вы под каждый класс модели будете создавать набор из всех возможных исключений? Это кажется не очень оптимальным, передавайте в метод класс в котором ошибка произошла и пишите в лог

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
Блок else не нужен, можно просто return, поскольку у вас внутри ифа есть return тоже

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final GenreDbStorage genreDbStorage;
Инжектите в класс интерфейс, а не реализацию, такой подход считается более верным

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmGenre/GenreDbStorage.java
> +    public List<Film> setGenres(List<Film> films) {
Если метода нет в интерфейсе, делайте его приватным

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmMpa/MpaDbStorage.java
> +    public Mpa getMpaById(long id) {
Отсутствует ovveride

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQuery = "SELECT * " +
В 1 строчку запрос влезает

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +        } else if (film.getName() == null || film.getName().isBlank()) {
А почему StringUtils убираете?

2023-12-15 16:49 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validator/GenreValidator.java
> +        if (genre.getName().isBlank()) {
getName null не вернет?

2023-12-15 16:49 UTC, Frilock commented on src/main/resources/schema.sql
> +    email    varchar NOT NULL UNIQUE,
Для полей нужно продумывать размерности и указывать их в скрипте

2023-12-15 16:49 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
От этого теста уже никакого смысла нет, поскольку проверка поднятия контекста осуществляется и в других тестах

2023-12-15 17:43 UTC, IgorShurov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQuery = "SELECT * " +
Считаю, что такой способ разделения улучшает читаемость когда...

2023-12-15 18:42 UTC, IgorShurov commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmGenre/GenreDbStorage.java
> +    public List<Film> setGenres(List<Film> films) {
Данный метод реализован в интерфейсе GenreStorage

2023-12-16 10:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmGenre/GenreDbStorage.java
> +    public List<Film> setGenres(List<Film> films) {
Тогда вешайте override

2023-12-16 10:36 UTC, Frilock approved these changes
Принято

2023-12-16 10:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmGenre/GenreDbStorage.java
> +        String sql = "DELETE FROM film_genre " + "WHERE film_id = ?;";
а плюс то зачем? просто в 1 строчку)

2023-12-16 10:36 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Нет смысла вообще в этом тесте

2023-12-16 15:53 UTC, merged